
version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: subtrack
      POSTGRES_PASSWORD: subtrackpass
      POSTGRES_DB: subtrack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U subtrack"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://subtrack:subtrackpass@postgres:5432/subtrack
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Running database migrations...' &&
        npx drizzle-kit push:pg &&
        echo 'Starting application...' &&
        npm start
      "

volumes:
  postgres_data:
